circleci: Add a new smoke test job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -93,6 +93,44 @@ jobs:
             - ~/.m2
           key: v1-dependencies-{{ checksum "pom.xml" }}
 
+  smoke_test:
+    docker:
+      - image: cimg/openjdk:17.0
+    steps:
+      - checkout
+      - show_java_version
+      - restore_cache:
+          keys:
+            - v1-dependencies-{{ checksum "pom.xml" }}
+            - v1-dependencies-
+      - setup_remote_docker
+
+      - run:
+          name: Build Docker image
+          command: |
+            docker build -t unconv-spring:test .
+
+      - run:
+          name: Run container
+          command: |
+            docker run -d -p 8080:8080 --name unconv-spring-container unconv-spring:test
+
+      - run:
+          name: Wait for container and test HTTP endpoint
+          command: |
+            echo "Waiting for application to be ready..."
+            for i in {1..10}; do
+              if curl --fail http://localhost:8080/public/status/v1/version; then
+                echo "App is up!"
+                exit 0
+              fi
+              echo "App not ready yet... retrying in 5s"
+              sleep 5
+            done
+            echo "App failed to start after retries. Showing container logs:"
+            docker logs unconv-spring-container
+            exit 1
+
   analyse:
     machine:
       image: ubuntu-2004:current
